# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0004_auto_20180410_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order'], 'verbose_name': '菜单配置', 'verbose_name_plural': '菜单配置'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='顺序'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon_class',
            field=models.CharField(max_length=32, null=True, verbose_name='图表类'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(default='#', max_length=64, verbose_name='URL地址'),
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
