# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0005_auto_20180410_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_name',
            field=models.CharField(default='#', max_length=64, verbose_name='URL Name'),
        ),
    ]
