# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0006_menu_url_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='url_name',
            new_name='url_names',
        ),
    ]
