# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0007_auto_20180410_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url_names',
            field=models.CharField(default='', max_length=64, verbose_name='URL Name'),
        ),
    ]
