# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0008_auto_20180410_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/static/img/profile-photos/1.png', max_length=256, verbose_name='头像'),
        ),
    ]
