# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0011_auto_20180410_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon_class',
            field=models.CharField(max_length=32, null=True, verbose_name='图标类'),
        ),
    ]
