# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0012_auto_20180411_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='顺序'),
        ),
    ]
