# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0017_auto_20180411_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='caption',
            field=models.CharField(blank=True, default='无标题', max_length=32, verbose_name='标题'),
        ),
    ]
