# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAdmin', '0020_auto_20180411_2049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([]),
        ),
    ]
